version: "3.8"

services:
  redis_db:
    image: redis:latest
    container_name: RedisDB_Container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
    driver: local
